# Generated by Django 6.0.6 on 2026-06-04 19:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('learning_style', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style', models.CharField(choices=[('visual', 'Visual Learner'), ('auditory', 'Auditory Learner'), ('reading', 'Reading/Writing Learner'), ('kinesthetic', 'Kinesthetic Learner'), ('mixed', 'Mixed/Combination')], max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('concentration_level', models.CharField(choices=[('low', 'Low (20-30 min)'), ('medium', 'Medium (45-60 min)'), ('high', 'High (90+ min)')], max_length=20)),
                ('subjects_studying', models.TextField(help_text='Comma-separated list of subjects')),
                ('academic_goals', models.TextField()),
                ('study_challenges', models.TextField()),
                ('available_hours_per_day', models.FloatField(default=2.0)),
                ('preferred_study_times', models.CharField(default='Evening', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('generated_plan', models.TextField()),
                ('weekly_schedule', models.TextField(blank=True, null=True)),
                ('study_techniques', models.TextField(blank=True, null=True)),
                ('revision_schedule', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('study', 'Study Session'), ('revision', 'Revision'), ('practice', 'Practice Test')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('duration_minutes', models.IntegerField()),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('missed', 'Missed')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lesson.studyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_study_minutes', models.IntegerField(default=0)),
                ('sessions_completed', models.IntegerField(default=0)),
                ('goals_achieved', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
